# -*- coding: utf-8 -*-
"""Project IR JSON -> HCB recompiler."""
from __future__ import annotations

import argparse
from pathlib import Path

from hcb_ir_core import write_hcb_from_ir


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Recompile fvp_analysis HCB IR JSON back to HCB.")
    p.add_argument("input_ir", help="Input .ir.json generated by hcb_to_ir.py")
    p.add_argument("-o", "--output", required=True, help="Output .hcb/.chb path")
    p.add_argument("--nls", default=None, choices=["sjis", "gbk", "utf8"], help="Override IR encoding")
    return p


def main() -> None:
    args = build_parser().parse_args()
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    write_hcb_from_ir(args.input_ir, out, nls=args.nls)
    print(f"HCB: {out}")


if __name__ == "__main__":
    main()
