-- Generated by SPEAK function GUI builder
-- This is a Lua-like template sketch, not full HCB source.
-- speak_block_index = 1
-- previous_block_sizes = []
-- auto_base_addr = True
-- function_base = 0x00000004
-- write_encoding = gbk
-- tmp_size = 295 bytes
-- next_function_base = 0x0000012B

function ShowSpeakerName_Kuro(...) 
  -- 固定部分：名字栏样式/角色显示编号
  G[227] = 1
  __ret = f_000019E0(G[227])  -- SetupSpeakerNameStyle
  if G[2001] in {0, 2, 4, 6} then
    G[2001] = G[2001] + 1
  end

  local mode = STACK[-3]
  if mode == -1 then
    SetAndPrintSpeakerName("　 ？？？ 　", "　？クロ　　")
    SyncSpeakerState(G[227], true)
    goto common_end
  end
  if mode == 10 then
    SetAndPrintSpeakerName("　　小黑　　", nil)
    SyncSpeakerState(G[227], true)
    goto common_end
  end
  if mode == 15 then
    SetAndPrintSpeakerName("　　小笨猫　　", nil)
    SyncSpeakerState(G[227], true)
    goto common_end
  end

  -- 默认分支
  SetAndPrintSpeakerName("", nil)
  SyncSpeakerState(G[227], true)
  if G[2001] in {0, 1, 4, 5} then
    G[2001] = G[2001] + 2
  end

  ::common_end::
  G[29] = 1
  G[293] = STACK[-4]
  G[294] = STACK[-2]
  G[295] = f_0008D409(1)
  return
end

-- raw_tmp_hex:
-- 01 03 00 0C 01 15 E3 00 0F E3 00 02 E0 19 00 00 0F D1 07 0C 00 22 0F D1 07 0C 02 22 21 0F D1 07 0C 04 22 21 0F D1 07 0C 06 22 21 07 3D 00 00 00 0F D1 07 0C 01 1A 15 D1 07 10 FD 0C FF 22 07 78 00 00 00 0E 0D A1 A1 20 A3 BF A3 BF A3 BF 20 A1 A1 00 0E 0D A1 A1 A3 BF A5 AF A5 ED A1 A1 A1 A1 00 02 DA CC 04 00 0F E3 00 09 02 B8 77 09 00 06 0F 01 00 00 10 FD 0C 0A 22 07 A5 00 00 00 0E 0D A1 A1 A1 A1 D0 A1 BA DA A1 A1 A1 A1 00 08 02 DA CC 04 00 0F E3 00 09 02 B8 77 09 00 06 0F 01 00 00 10 FD 0C 0F 22 07 D4 00 00 00 0E 0F A1 A1 A1 A1 D0 A1 B1 BF C3 A8 A1 A1 A1 A1 00 08 02 DA CC 04 00 0F E3 00 09 02 B8 77 09 00 06 0F 01 00 00 0E 01 00 08 02 DA CC 04 00 0F E3 00 09 02 B8 77 09 00 0F D1 07 0C 00 22 0F D1 07 0C 01 22 21 0F D1 07 0C 04 22 21 0F D1 07 0C 05 22 21 07 0F 01 00 00 0F D1 07 0C 02 1A 15 D1 07 0C 01 15 1D 00 10 FC 15 25 01 10 FE 15 26 01 0C 01 02 09 D4 08 00 14 15 27 01 04 04