-- Generated by CG display wrapper GUI builder
-- This is a Lua-like template sketch, not full HCB source.
-- function family skeleton:
--   G[flag_global] = true
--   f_init()
--   f_show(arg1..arg10)
--   f_finalize(arg1..arg3)
-- block_index = 1
-- previous_block_sizes = []
-- auto_base_addr = False
-- function_base = 0x00002403
-- init_stack args=6 locals=0
-- flag_global = G[2124]
-- init_addr = 0x00010271
-- show_addr = 0x00051420
-- finalize_addr = 0x00010298
-- write_encoding = sjis
-- tmp_size = 56 bytes
-- next_function_base = 0x0000243B

function ShowCG_KURO_e011a1(...) 
  G[2124] = true
  __ret = f_00010271()
  __ret = f_00051420("KURO_e011a1", STACK[-7], 1, nil, STACK[-6], STACK[-5], STACK[-4], STACK[-3], nil, nil)
  __ret = f_00010298(nil, nil, STACK[-2])
  return
end

-- arg_source_notes:
--   show_arg1: 显示参数1 / 通常是资源名字符串，如 KURO_e011b1
--   show_arg2: 显示参数2 / 通常是第1输入槽，如 STACK[-7]
--   show_arg3: 显示参数3 / 通常是固定常量 1
--   show_arg4: 显示参数4 / 通常为 nil
--   show_arg5: 显示参数5 / 通常是第2输入槽，如 STACK[-6]
--   show_arg6: 显示参数6 / 通常是第3输入槽，如 STACK[-5]
--   show_arg7: 显示参数7 / 通常是第4输入槽，如 STACK[-4]
--   show_arg8: 显示参数8 / 通常是第5输入槽，如 STACK[-3]
--   show_arg9: 显示参数9 / 通常为 nil
--   show_arg10: 显示参数10 / 通常为 nil
--   finalize_arg1: 后处理参数1 / 通常为 nil
--   finalize_arg2: 后处理参数2 / 通常为 nil
--   finalize_arg3: 后处理参数3 / 通常是第6输入槽，如 STACK[-2]

-- raw_tmp_hex:
-- 01 06 00 09 15 4C 08 02 71 02 01 00 0E 0C 4B 55 52 4F 5F 65 30 31 31 61 31 00 10 F9 0C 01 08 10 FA 10 FB 10 FC 10 FD 08 08 02 20 14 05 00 08 08 10 FE 02 98 02 01 00 04