-- Generated by SPEAK_CharacterNameText GUI builder
-- This is a Lua-like template sketch, not full HCB source.
-- speak_block_index = 1
-- previous_block_sizes = []
-- auto_base_addr = False
-- function_base = 0x000019E0
-- init_stack args=1 locals=1
-- style_stack_index = -2
-- palette_func_addr = 0x0008CC08
-- text_color_syscall_id = 112
-- text_out_size_syscall_id = 120
-- write_encoding = sjis
-- special_start_count = 3
-- regular_count = 4
-- range_count = 2
-- tmp_size = 481 bytes
-- next_function_base = 0x00001BC1

function SPEAK_CharacterNameText_Sample(...) 
  local style_id = STACK[-2]

  -- 特殊起始分支
  -- 基础样式
  if style_id == 0 then
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 11, 100)
    goto function_end
  end

  -- 特殊样式 98
  if style_id == 98 then
    f_0008CC08(0, 51)
    TextColor(8, 10, 51, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 51, 100)
    goto function_end
  end

  -- 特殊样式 99
  if style_id == 99 then
    f_0008CC08(0, 51)
    TextColor(8, 10, 51, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 51, 100)
    goto function_end
  end

  -- 常规离散分支
  -- 常规离散样式示例
  if style_id == 1 then
    f_0008CC08(1, 52)
    TextColor(8, 10, 52, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 52, 100)
    goto function_end
  end

  -- 特殊映射示例
  if style_id == 13 then
    f_0008CC08(51, 90)
    TextColor(8, 10, 90, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 90, 100)
    goto function_end
  end

  -- 离散尾项示例
  if style_id == 25 then
    f_0008CC08(25, 76)
    TextColor(8, 10, 76, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 76, 100)
    goto function_end
  end

  if style_id == 2 then
    f_0008CC08(2, 53)
    TextColor(8, 10, 52, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 52, 100)
    goto function_end
  end

  -- 区间离散分支
  -- 区间映射 A
  if style_id >= 30 and style_id <= 39 then
    f_0008CC08(51, 90)
    TextColor(8, 10, 90, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 90, 100)
    goto function_end
  end

  -- 区间映射 B
  if style_id >= 40 then
    f_0008CC08(52, 91)
    TextColor(8, 10, 91, 100)
    TextOutSize(0, 5, nil)
    TextColor(0, 10, 91, 100)
    goto function_end
  end

  ::function_end::
  return
end

-- raw_tmp_hex:
-- 01 01 01 10 FE 0C 00 22 07 05 1A 00 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 0B 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 62 22 07 3B 1A 00 00 0C 00 0C 33 02 08 CC 08 00 0C 08 0C 0A 0C 33 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 33 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 63 22 07 71 1A 00 00 0C 00 0C 33 02 08 CC 08 00 0C 08 0C 0A 0C 33 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 33 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 01 22 07 A7 1A 00 00 0C 01 0C 34 02 08 CC 08 00 0C 08 0C 0A 0C 34 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 34 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 0D 22 07 DD 1A 00 00 0C 33 0C 5A 02 08 CC 08 00 0C 08 0C 0A 0C 5A 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 5A 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 19 22 07 13 1B 00 00 0C 19 0C 4C 02 08 CC 08 00 0C 08 0C 0A 0C 4C 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 4C 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 02 22 07 49 1B 00 00 0C 02 0C 35 02 08 CC 08 00 0C 08 0C 0A 0C 34 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 34 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 1E 25 07 89 1B 00 00 10 FE 0C 27 27 07 89 1B 00 00 0C 33 0C 5A 02 08 CC 08 00 0C 08 0C 0A 0C 5A 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 5A 0C 64 03 70 00 06 BF 1B 00 00 10 FE 0C 28 25 07 BF 1B 00 00 0C 34 0C 5B 02 08 CC 08 00 0C 08 0C 0A 0C 5B 0C 64 03 70 00 0C 00 0C 05 08 03 78 00 0C 00 0C 0A 0C 5B 0C 64 03 70 00 06 BF 1B 00 00 04 04